name: Build spack package
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 2"

jobs:
  spack:
    runs-on: ubuntu-latest
    container:
      image: spack/${{ matrix.distribution }}
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - almalinux8
          - almalinux9
          - ubuntu-noble
    steps:
      - uses: actions/checkout@v5
      - name: Set up spack repositories
        run: |
          . /opt/spack/share/spack/setup-env.sh
          spack repo add spack_repo/macaulay2
          cd $(spack location --repo builtin)
          git fetch origin develop
          git checkout origin/develop
      - name: Install Macaulay2
        run: |
          . /opt/spack/share/spack/setup-env.sh
          spack install --verbose macaulay2
